name: Apply SW4HW Standards
on: 
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standardize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cloud-action test
        uses: xanaduAI/cloud-actions/og/unit@main
        with:
          key: ${{ secrets.XANADU_OG_QUBOT }}
          path: tests/instruments

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-artifacts-${{ github.head_ref }}
          path: ./**/*.xml
