name: Apply SW4HW Standards
on: 
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standardize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Pip install
        shell: bash
        run: 
          pip install -r ./requirements.txt pytest pytest-cov

      - name: Run tests
        shell: bash
        run: 
          python -m pytest instruments --showlocals --full-trace --cov=pymeasure --cov-report xml:coverage.xml --cov-report term-missing --junitxml junit.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-artifacts-${{ github.head_ref }}
          path: ./**/*.xml
